CVeator.Web/ViewModels/SkillsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CVeator.Entities;

namespace CVeator.Web.ViewModels
{
    public class SkillsViewModel
    {

        public string SkillName { get; set; }
        public string level { get; set; }


        public int PersonalInfo_ID { get; set; }

        [ForeignKey("PersonalInfo_ID")]
        public virtual PersonalInfo personalInfo { get; set; }
    }

}

CVeator.Web/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVeator.Entities;
using CVeatorServices;
using CVeator.Web.ViewModels;

namespace CVeator.Web.Controllers
{
    public class SkillsController : Controller
    {
        SkillsServices SkillsServices = new SkillsServices();
        public ActionResult Index()
        {
            var AllSkill = SkillsServices.GetAllSkill();
            return View(AllSkill);
        }
        
        public ActionResult Create(int CvID)
        {
            SkillsViewModel model = new SkillsViewModel();
            model.PersonalInfo_ID = CvID;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(Skill Skill)
        {
            SkillsServices.SaveSkill(Skill);
            return RedirectToAction("Create", "Summeries", new { CvID = Skill.PersonalInfo_ID });
        }

        public ActionResult Edit(int ID)
        {
           var Skill = SkillsServices.GetSkillById(ID);
            return View(Skill);
        }
        [HttpPost]
        public ActionResult Edit(Skill Skill)
        {
            SkillsServices.UpdateSkill(Skill);
            return RedirectToAction("index");
        }
        //public ActionResult Delete(int ID)
        //{
        //    var CV = cvServices.GetCVById(ID);
        //    return View(CV);
        //    //return PartialView(auction);
        //}
        [HttpPost]
        public ActionResult Delete(Skill Skill)
        {
            SkillsServices.DeleteSkill(Skill);
            return RedirectToAction("index");
        }
    }
}

CVeator.Web/Views/Skills/Create.cshtml
@model CVeator.Web.ViewModels.SkillsViewModel

<h2>Create Skill</h2>

<div class="container">
    <form id="CreateForm" method="post">
        <input type="hidden" name="PersonalInfo_ID" value="@Model.PersonalInfo_ID" />
        <div class="form-group">
            <label>SkillName</label>
            <input name="SkillName" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label> level</label>
            <input name="level" class="form-control" />
            <br />
        </div>
        <button type="submit" id="SaveButton">Save</button>
        <a href="@Url.Action("Create","Summeries")" class="btn btn-default">Next</a>

    </form>


</div>
@*<script>
    $("#SaveButton").click(function () {

        $.ajax({
            url: "@Url.Action("Create","Skills")",
            type: "post",
            data: $("#CreateForm").serialize()
        }).done(function (response) {
            $("#ListArea").html(response);
           $("#formModal").modal("toggle");
        });
    });
</script>*@

CVeator.Web/Views/Skills/Edit.cshtml
@model CVeator.Entities.Skill



<h2>Edit Skill</h2>

<div class="container">
    <form id="EditForm">
        <input type="hidden" name="ID" class="form-control" value="@Model.ID" />

        <div class="form-group">
            <label>SkillName</label>
            <input name="SkillName" class="form-control" value="@Model.SkillName" />
            <br />
        </div>
        <div class="form-group">
            <label> level</label>
            <input name="level" class="form-control" value="@Model.level" />
            <br />
        </div>

        <button type="button" id="SaveButton">Save</button>

    </form>

</div>
<script>
    $("#SaveButton").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Edit","Skills")",
            type: "post",
            data: $("#EditForm").serialize()
        }).done(function (response) {
            $("#ListArea").html(response);
           $("#formModal").modal("toggle");
        });
    });
</script>

CVeator.Web/Views/Skills/Index.cshtml
@model List<CVeator.Entities.Skill>


<div id="ListArea" class="container">
    <table class="table table-bordered" style="margin-top:10px">

        <thaed>
            <tr>

                <th> Skill Name</th>
                <th> level</th>

                <th> Actions</th>

            </tr>

        </thaed>

        <tbody>
            @foreach (var skill in Model)
            {
                <tr>
                    <td> @skill.SkillName </td>
                    <td> @skill.level</td>

                    <td>
                        <button class="btn btn-danger DeleteBtn" data-id="@skill.ID">Delete</button>
                        <button class="btn btn-success EditBtn" data-id="@skill.ID">Edit</button>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div>
        <button id="CreateBtn">Create Skill</button>
    </div>

    <div id="ContentArea">
    </div>
</div>

<script>
    $("#CreateBtn").click(function () {
        $.ajax({
            url: "@Url.Action("Create","skills")",
            method: "get"
        }).done(function (response){
            $("#ContentArea").html(response);

        });
    });
     //$("#CreateBtn").click(function () {
     //           $.ajax({
     //               url: "CVs/create/",
     //               method: "get"
     //           }).done(function (response) {
     //               debugger;
     //               $("#ContentArea").html(response);
     //           });
     //       });

           $(".EditBtn").click(function () {
               $.ajax({
                   url: "@Url.Action("Edit","skills")",
                   method: "get",
                   data: {
                      ID: $(this).attr("data-id")
                   }
               }).done(function (response) {
                   $("#ContentArea").html(response);
               });
           });
           $(".DeleteBtn").click(function () {
               var result = confirm("Are you sure to delete this Auction!");
               if (result == true) {
                  $.ajax({
                     url: "@Url.Action("Delete","skills")",
                    method: "post",
                    data: {
                          ID: $(this).attr("data-id")
                    }
                  }).done(function (response) {
                      $("#ListArea").html(response);
                  });
               }
           });
</script>