CVeator.Web/ViewModels/CVViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CVeator.Entities;

namespace CVeator.Web.ViewModels
{
    public class CVViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public Decimal PhoneNumber { get; set; }
        public string PictureURL { get; set; }

        public virtual List<Experience> Experiences { get; set; }
        public virtual List<Education> Educations { get; set; }
        public virtual List<Skill> Skills { get; set; }
        public virtual List<Summery> Summeries { get; set; }
    }
    public class CVPreview
    {
        public PersonalInfo CV { get; set; }
    }
}

CVeator.Web/Controllers/CVsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVeator.Entities;
using CVeatorServices;

namespace CVeator.Web.Controllers
{
    public class CVsController : Controller
    {
        CVsServices cvServices = new CVsServices();
        // GET: CVs
        public ActionResult Index()
        {
            //PersonalInfo personalInfo = new PersonalInfo();

            var AllCVs = cvServices.GetAllCVs();
            return View(AllCVs);
        }
        
        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(PersonalInfo personalInfo)
        {
            cvServices.SaveCV(personalInfo);
            return RedirectToAction("index");
        }

        public ActionResult Edit(int ID)
        {
           var cv = cvServices.GetCVById(ID);
            return View(cv);
        }
        [HttpPost]
        public ActionResult Edit(PersonalInfo personalInfo)
        {
            cvServices.UpdateCV(personalInfo);
            return RedirectToAction("index");
        }
        //public ActionResult Delete(int ID)
        //{
        //    var CV = cvServices.GetCVById(ID);
        //    return View(CV);
        //    //return PartialView(auction);
        //}
        [HttpPost]
        public ActionResult Delete(PersonalInfo personalInfo)
        {
            cvServices.DeleteCV(personalInfo);
            return RedirectToAction("index");
        }
    }
}

CVeator.Web/Controllers/ExperiencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVeator.Entities;
using CVeator.Web.ViewModels;
using CVeatorServices;

namespace CVeator.Web.Controllers
{
    public class ExperiencesController : Controller
    {
        Experience Experience = new Experience();
        ExperiencesServices ExperienceServices = new ExperiencesServices();
        public ActionResult Index()
        {
            var AllExperiences = ExperienceServices.GetAllExperience();
            return View(AllExperiences);
        }
        
        public ActionResult Create(int CvID)
        {
            ExperienceViewModel model = new ExperienceViewModel();
            model.PersonalInfo_ID = CvID;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(Experience Experience)
        
        {
            ExperienceServices.SaveExperience(Experience);
            return RedirectToAction("Create", "Educations",new {CvID = Experience.PersonalInfo_ID });
        }

        public ActionResult Edit(int ID)
        {
           var Experience = ExperienceServices.GetExperienceById(ID);
            return View(Experience);
        }
        [HttpPost]
        public ActionResult Edit(Experience Experience)
        {
            ExperienceServices.UpdateExperience(Experience);
            return RedirectToAction("index");
        }
        //public ActionResult Delete(int ID)
        //{
        //    var CV = cvServices.GetCVById(ID);
        //    return View(CV);
        //    //return PartialView(auction);
        //}
        [HttpPost]
        public ActionResult Delete(Experience Experience)
        {
            ExperienceServices.DeleteExperience(Experience);
            return RedirectToAction("index");
        }
    }
}

CVeator.Web/Views/CVs/Create.cshtml
<h2>Create CV</h2>

<form id="CreateForm" method="post">
    <div>
        <div class="form-row">
            <div class="col-lg-6 col-md-6">
                <label class="form-group">FirstName</label>
                <input class="form-control" name="FirstName" placeholder="First Name" />
                <br />
            </div>
            <div class="col-lg-6 col-md-6">
                <label class="form-group"> LastName</label>
                <input class="form-control" name="LastName" placeholder="Last Name" />
                <br />
            </div>
        </div>

        <label class="form-group">Address</label>
        <input class="form-control" name="Address" />
        <br />

        <label class="form-group">City</label>
        <input class="form-control" name="City" />
        <br />

        <label class="form-group">ZipCode</label>
        <input class="form-control" name="ZipCode" />
        <br />

        <label class="form-group">Country</label>
        <input class="form-control" name="Country" />
        <br />

        <label class="form-group">Email</label>
        <input class="form-control" name="Email" />
        <br />

        <label class="form-group">PhoneNumber</label>
        <input class="form-control" name="PhoneNumber" />
        <br />
        <button class="btn btn-success" type="submit" id="SaveButton">Save</button>

        @*<a id="SaveButton" href="@Url.Action("Create","Experiences")" class="btn btn-default">Next</a>*@
    </div>


</form>




@*<script>
    $("#SaveButton").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Create","CVs")",
            type: "post",
            data: $("#CreateForm").serialize()
        }).done(function (response) {
           $("#ListArea").html(response);
        });
    });
</script>*@

CVeator.Web/Views/CVs/Edit.cshtml
@model CVeator.Entities.PersonalInfo



<h2>Edit CV</h2>

<div  class="container">
    <form id="EditForm">
        <input type="hidden" name="ID" value="@Model.ID" />

        <div class="form-group">
            <label>FirstName</label>
            <input name="FirstName" value="@Model.FirstName" />
            <br />
        </div>
        <div class="form-group">
            <label> LastName</label>
            <input name="LastName" value="@Model.LastName" />
            <br />
        </div>
        <div class="form-group">
            <label>Address</label>
            <input name="Address" value="@Model.Address" />
            <br />
        </div>
        <div class="form-group">
            <label>City</label>
            <input name="City" value="@Model.City" />
            <br />
        </div>
        <div class="form-group">
            <label>ZipCode</label>
            <input name="ZipCode" value="@Model.ZipCode" />
            <br />
        </div>
        <div class="form-group">
            <label>Country</label>
            <input name="Country" value="@Model.Country" />
            <br />
        </div>
        <div class="form-group">
            <label>Email</label>
            <input name="Email" value="@Model.Email" />
            <br />
        </div>
        <div class="form-group">
            <label>PhoneNumber</label>
            <input name="PhoneNumber" value="@Model.PhoneNumber" />
            <br />
        </div>

        <button type="button" id="SaveButton">Save</button>

</form>

</div>
<script>
    $("#SaveButton").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Edit","CVs")",
            type: "post",
            data: $("#EditForm").serialize()
        }).done(function (response) {
            $("#ListArea").html(response);
           $("#formModal").modal("toggle");
        });
    });
</script>

CVeator.Web/Views/CVs/Index.cshtml
@model List<CVeator.Entities.PersonalInfo>


    <div id="ListArea" class="container">
        <table class="table table-bordered" style="margin-top:10px">

            <thaed>
                <tr>

                    <th> First Name</th>
                    <th> Last Name</th>
                    <th> Address</th>
                    <th> City</th>
                    <th> Zip Code</th>
                    <th> Country</th>
                    <th> Email</th>
                    <th> Phone Number</th>
                    <th> PictureURL</th>

                    <th> Actions</th>

                </tr>

            </thaed>

            <tbody>
                @foreach (var Info in Model)
                {
                    <tr>
                        <td> @Info.FirstName </td>
                        <td> @Info.LastName</td>
                        <td> @Info.Address</td>
                        <td> @Info.City</td>
                        <td> @Info.ZipCode</td>
                        <td> @Info.Country</td>
                        <td> @Info.Email</td>
                        <td> @Info.PhoneNumber</td>
                        <td> @Info.PictureURL</td>

                        <td>
                            <button class="btn btn-danger DeleteBtn" data-id="@Info.ID">Delete</button>
                            <button class="btn btn-success EditBtn" data-id="@Info.ID">Edit</button>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
        <div>
            <button id="CreateBtn">Create CV</button>
        </div>

        <div id="ContentArea">
        </div>
    </div>

<script>
    $("#CreateBtn").click(function () {
        $.ajax({
            url: "@Url.Action("Create","CVs")",
            method: "get"
        }).done(function (response){
            $("#ContentArea").html(response);

        });
    });
     //$("#CreateBtn").click(function () {
     //           $.ajax({
     //               url: "CVs/create/",
     //               method: "get"
     //           }).done(function (response) {
     //               debugger;
     //               $("#ContentArea").html(response);
     //           });
     //       });
    
           $(".EditBtn").click(function () {
               debugger;
               $.ajax({
                   url: "@Url.Action("Edit","CVs")",
                   method: "get",
                   data: {
                      ID: $(this).attr("data-id")
                   }
               }).done(function (response) {
                   debugger;
                   $("#ContentArea").html(response);
               });
           });
           $(".DeleteBtn").click(function () {
               var result = confirm("Are you sure to delete this Auction!");
               if (result == true) {
                  $.ajax({
                     url: "@Url.Action("Delete","CVs")",
                    method: "post",
                    data: {
                          ID: $(this).attr("data-id")
                    }
                  }).done(function (response) {
                      $("#ListArea").html(response);
                  });
               }
           });
</script>