CVeator.Web/ViewModels/EducationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CVeator.Entities;

namespace CVeator.Web.ViewModels
{
    public class EducationViewModel
    {


        public string SchoolName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Degree { get; set; }
        public string FielOfStudy { get; set; }
        public DateTime GraduationDate { get; set; }


        public int PersonalInfo_ID { get; set; }

        [ForeignKey("PersonalInfo_ID")]
        public virtual PersonalInfo personalInfo { get; set; }
    }

}

CVeator.Web/Controllers/EducationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVeator.Entities;
using CVeator.Web.ViewModels;
using CVeatorServices;

namespace CVeator.Web.Controllers
{
    public class EducationsController : Controller
    {
        EducationsServices EducationsServices = new EducationsServices();
        public ActionResult Index()
        {
            var AllEducations = EducationsServices.GetAllEducation();
            return View(AllEducations);
        }
        
        public ActionResult Create(int CvID)
        {
            EducationViewModel model = new EducationViewModel();
            model.PersonalInfo_ID = CvID;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(Education Education)
        {
            EducationsServices.SaveEducation(Education);
            return RedirectToAction("Create", "Skills", new { CvID = Education.PersonalInfo_ID });
        }

        public ActionResult Edit(int ID)
        {
           var Education = EducationsServices.GetEducationById(ID);
            return View(Education);
        }
        [HttpPost]
        public ActionResult Edit(Education Education)
        {
            EducationsServices.UpdateEducation(Education);
            return RedirectToAction("index");
        }
        //public ActionResult Delete(int ID)
        //{
        //    var CV = cvServices.GetCVById(ID);
        //    return View(CV);
        //    //return PartialView(auction);
        //}
        [HttpPost]
        public ActionResult Delete(Education Education)
        {
            EducationsServices.DeleteEducation(Education);
            return RedirectToAction("index");
        }
    }
}

CVeator.Web/Views/Educations/Create.cshtml
<h2>Create Education</h2>

<div class="container">
    <form id="CreateForm" method="post">
        <input type="hidden" name="PersonalInfo_ID" value="@Model.PersonalInfo_ID" />
        <div class="form-group">
            <label>SchoolName</label>
            <input name="SchoolName" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label>City</label>
            <input name="City" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label>State</label>
            <input name="State" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label>Degree</label>
            <input name="Degree" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label>FielOfStudy</label>
            <input name="FielOfStudy" class="form-control" />
            <br />
        </div>
        <div class="form-group">
            <label>GraduationDate</label>
            <input name="GraduationDate" class="form-control" />
            <br />
        </div>
        <button type="submit" id="SaveButton">Save</button>

        <a href="@Url.Action("Create","Skills")" class="btn btn-default">Next</a>
    </form>


</div>
@*<script>
    $("#SaveButton").click(function () {

        $.ajax({
            url: "@Url.Action("Create","Educations")",
            type: "post",
            data: $("#CreateForm").serialize()
        }).done(function (response) {
            $("#ListArea").html(response);
           $("#formModal").modal("toggle");
        });
    });
</script>*@

CVeator.Web/Views/Educations/Edit.cshtml
@model CVeator.Entities.Education



<h2>Edit Experience</h2>

<div class="container">
    <form id="EditForm">
        <input type="hidden" name="ID" class="form-control" value="@Model.ID" />

        <div class="form-group">
            <label>SchoolName</label>
            <input name="SchoolName" class="form-control" value="@Model.SchoolName" />
            <br />
        </div>
        <div class="form-group">
            <label>City</label>
            <input name="City" class="form-control" value="@Model.City" />
            <br />
        </div>
        <div class="form-group">
            <label>State</label>
            <input name="State" class="form-control" value="@Model.State" />
            <br />
        </div>
        <div class="form-group">
            <label>Degree</label>
            <input name="Degree" class="form-control" value="@Model.Degree" />
            <br />
        </div>
        <div class="form-group">
            <label>FielOfStudy</label>
            <input name="FielOfStudy" class="form-control" value="@Model.FielOfStudy" />
            <br />
        </div>
        <div class="form-group">
            <label>GraduationDate</label>
            <input name="GraduationDate" class="form-control" value="@Model.GraduationDate" />
            <br />
        </div>

        <button type="button" id="SaveButton">Save</button>

    </form>

</div>
<script>
    $("#SaveButton").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Edit","Educations")",
            type: "post",
            data: $("#EditForm").serialize()
        }).done(function (response) {
            $("#ListArea").html(response);
           $("#formModal").modal("toggle");
        });
    });
</script>

CVeator.Web/Views/Educations/Index.cshtml
@model List<CVeator.Entities.Education>


<div id="ListArea" class="container">
    <table class="table table-bordered" style="margin-top:10px">

        <thaed>
            <tr>

                <th> SchoolName</th>
                <th> City</th>
                <th> State</th>
                <th> Degree</th>
                <th> FielOfStudy</th>
                <th> GraduationDate</th>

                <th> Actions</th>

            </tr>

        </thaed>

        <tbody>
            @foreach (var edu in Model)
            {
                <tr>
                    <td> @edu.SchoolName </td>
                    <td> @edu.City</td>
                    <td> @edu.State</td>
                    <td> @edu.Degree</td>
                    <td> @edu.FielOfStudy</td>
                    <td> @edu.GraduationDate</td>

                    <td>
                        <button class="btn btn-danger DeleteBtn" data-id="@edu.ID">Delete</button>
                        <button class="btn btn-success EditBtn" data-id="@edu.ID">Edit</button>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div>
        <button id="CreateBtn">Create Education</button>
    </div>

    <div id="ContentArea">
    </div>
</div>

<script>
    $("#CreateBtn").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Create","Educations")",
            method: "get"
        }).done(function (response){
            $("#ContentArea").html(response);

        });
    });
     //$("#CreateBtn").click(function () {
     //           $.ajax({
     //               url: "CVs/create/",
     //               method: "get"
     //           }).done(function (response) {
     //               debugger;
     //               $("#ContentArea").html(response);
     //           });
     //       });

           $(".EditBtn").click(function () {
               debugger;
               $.ajax({
                   url: "@Url.Action("Edit","Educations")",
                   method: "get",
                   data: {
                      ID: $(this).attr("data-id")
                   }
               }).done(function (response) {
                   debugger;
                   $("#ContentArea").html(response);
               });
           });
           $(".DeleteBtn").click(function () {
               var result = confirm("Are you sure to delete this Auction!");
               if (result == true) {
                  $.ajax({
                     url: "@Url.Action("Delete","Educations")",
                    method: "post",
                    data: {
                          ID: $(this).attr("data-id")
                    }
                  }).done(function (response) {
                      $("#ListArea").html(response);
                  });
               }
           });
</script>