CVeator.Web/ViewModels/SummeriesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CVeator.Entities;

namespace CVeator.Web.ViewModels
{
    
    public class SummeriesViewModel
    {
       
        public string ProfessionalSummery { get; set; }


        public int PersonalInfo_ID { get; set; }

        [ForeignKey("PersonalInfo_ID")]
        public virtual PersonalInfo personalInfo { get; set; }
    }

}

CVeator.Web/Controllers/SummeriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVeator.Entities;
using CVeator.Web.ViewModels;
using CVeatorServices;

namespace CVeator.Web.Controllers
{
    public class SummeriesController : Controller
    {
        SummeriesServices SummeriesServices = new SummeriesServices();
        public ActionResult Index()
        {
            var AllSummery = SummeriesServices.GetAllSummeries();
            return View(AllSummery);
        }

        
        public ActionResult Create(int CvID)
        {
            SummeriesViewModel model = new SummeriesViewModel();
            model.PersonalInfo_ID= CvID;
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(Summery Summery)
        {
            SummeriesServices.SaveSummery(Summery);
            return RedirectToAction("CV1","CVsView/1");
        }

        public ActionResult Edit(int ID)
        {
           var Summery = SummeriesServices.GetSummeryById(ID);
            return View(Summery);
        }
        [HttpPost]
        public ActionResult Edit(Summery Summery)
        {
            SummeriesServices.UpdateSummery(Summery);
            return RedirectToAction("index");
        }
        //public ActionResult Delete(int ID)
        //{
        //    var CV = cvServices.GetCVById(ID);
        //    return View(CV);
        //    //return PartialView(auction);
        //}
        [HttpPost]
        public ActionResult Delete(Summery Summery)
        {
            SummeriesServices.DeleteSummery(Summery);
            return RedirectToAction("index");
        }
    }
}

CVeator.Web/Views/Summeries/Create.cshtml
@model CVeator.Web.ViewModels.SummeriesViewModel

<h2>Create Summery</h2>

<div class="container">
    <form id="CreateForm" method="post">
        <input type="hidden" name="PersonalInfo_ID" value="@Model.PersonalInfo_ID" />
        @*<div class="form-group shadow-textarea">
                <label>Professional Summery</label>
                <textarea name="ProfessionalSummery" class="form-control" placeholder="Write something here..."></textarea>
            </div>*@
        <label>Professional Summery</label>
        <textarea name="ProfessionalSummery" id="summernote"></textarea>
        <script>
            $('#summernote').summernote({
                placeholder: 'Hello bootstrap 4',
                tabsize: 3,
                height: 100
            });
        </script>
        <button type="submit" id="SaveButton">Save</button>
    </form>

</div>

@*<script>
        $("#SaveButton").click(function () {

            $.ajax({
                url: "@Url.Action("Create","Summeries")",
                type: "post",
                data: $("#CreateForm").serialize()
            }).done(function (response) {
                $("#ListArea").html(response);
               $("#formModal").modal("toggle");
            });
        });
    </script>*@

CVeator.Web/Views/Summeries/Index.cshtml
@model List<CVeator.Entities.Summery>


<div id="ListArea" class="container">
    <table class="table table-bordered" style="margin-top:10px">

        <thaed>
            <tr>

                <th> Professional Summery</th>

                <th> Actions</th>

            </tr>

        </thaed>

        <tbody>
            @foreach (var Summery in Model)
            {
                <tr>
                    <td> @Summery.ProfessionalSummery </td>

                    <td>
                        <button class="btn btn-danger DeleteBtn" data-id="@Summery.ID">Delete</button>
                        <button class="btn btn-success EditBtn" data-id="@Summery.ID">Edit</button>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div>
        <button id="CreateBtn">Create Summery</button>
    </div>

    <div id="ContentArea">
    </div>
</div>

<script>
    $("#CreateBtn").click(function () {
        $.ajax({
            url: "@Url.Action("Create","Summeries")",
            method: "get"
        }).done(function (response){
            $("#ContentArea").html(response);

        });
    });
     //$("#CreateBtn").click(function () {
     //           $.ajax({
     //               url: "CVs/create/",
     //               method: "get"
     //           }).done(function (response) {
     //               debugger;
     //               $("#ContentArea").html(response);
     //           });
     //       });

           $(".EditBtn").click(function () {
               $.ajax({
                   url: "@Url.Action("Edit","Summeries")",
                   method: "get",
                   data: {
                      ID: $(this).attr("data-id")
                   }
               }).done(function (response) {
                   $("#ContentArea").html(response);
               });
           });
           $(".DeleteBtn").click(function () {
               var result = confirm("Are you sure to delete this Auction!");
               if (result == true) {
                  $.ajax({
                     url: "@Url.Action("Delete","Summeries")",
                    method: "post",
                    data: {
                          ID: $(this).attr("data-id")
                    }
                  }).done(function (response) {
                      $("#ListArea").html(response);
                  });
               }
           });
</script>